// <auto-generated />
using System;
using BookStoreV2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStoreV2.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190314010655_Genre")]
    partial class Genre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStoreV2.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("AuthorId");

                    b.ToTable("Author","dbo");

                    b.HasData(
                        new { AuthorId = new Guid("eceb8874-df41-4a64-9b6e-84bf8ce3315e"), FirstName = "Daniel", Genre = "Action", LastName = "Silva" },
                        new { AuthorId = new Guid("497a5440-588a-47de-9d2d-ee48ed10d110"), FirstName = "Andrew", Genre = "Medicine", LastName = "Weil" },
                        new { AuthorId = new Guid("d1d36299-029d-4851-8b95-b2bbdfb47254"), FirstName = "Tom", Genre = "Thriller", LastName = "Clancy" },
                        new { AuthorId = new Guid("0fa36c56-d64b-4858-9c36-852600ccdca1"), FirstName = "Lee", Genre = "Action", LastName = "Child" },
                        new { AuthorId = new Guid("90dca817-f00f-4db3-95ce-d53f3e8cfe8a"), FirstName = "Anthony", Genre = "Fiction", LastName = "Doeer" },
                        new { AuthorId = new Guid("19b5bbaf-f279-443f-9a92-f1c5092d4483"), FirstName = "Clinton", Genre = "Military", LastName = "Romesha" },
                        new { AuthorId = new Guid("f9d15bdc-4773-40af-8008-26c5642e777c"), FirstName = "Marcus", Genre = "Military", LastName = "Luttrell" },
                        new { AuthorId = new Guid("15557698-99c9-4596-981e-678d1ed0d78a"), FirstName = "Robert", Genre = "Thriller", LastName = "Ludlum" }
                    );
                });

            modelBuilder.Entity("BookStoreV2.Entities.Book", b =>
                {
                    b.Property<Guid>("BookdId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("BookdId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book","dbo");
                });

            modelBuilder.Entity("BookStoreV2.Entities.Book", b =>
                {
                    b.HasOne("BookStoreV2.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
