// <auto-generated />
using System;
using BookStoreV2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStoreV2.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190308025221_MoreSeedData")]
    partial class MoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStoreV2.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("AuthorId");

                    b.ToTable("Author","dbo");

                    b.HasData(
                        new { AuthorId = new Guid("e663678a-5c14-4fbb-a74e-fe6fa4e500b8"), FirstName = "Daniel", Genre = "Action", LastName = "Silva" },
                        new { AuthorId = new Guid("25cbb71c-ded8-457e-82bc-22f3e2823b74"), FirstName = "Andrew", Genre = "Medicine", LastName = "Weil" },
                        new { AuthorId = new Guid("c0f576e9-3949-40ad-abba-1d289a9702d3"), FirstName = "Tom", Genre = "Thriller", LastName = "Clancy" },
                        new { AuthorId = new Guid("3a2cd1f0-6900-4784-854a-ad4bf4ada625"), FirstName = "Lee", Genre = "Action", LastName = "Child" },
                        new { AuthorId = new Guid("2c355d64-e95a-4827-9638-81fd67abfc16"), FirstName = "Anthony", Genre = "Fiction", LastName = "Doeer" },
                        new { AuthorId = new Guid("f0be5e74-3537-478e-b4e1-9350be978195"), FirstName = "Clinton", Genre = "Military", LastName = "Romesha" },
                        new { AuthorId = new Guid("f4ab2d70-c04d-481c-b689-2c3e2c3c2297"), FirstName = "Marcus", Genre = "Military", LastName = "Luttrell" },
                        new { AuthorId = new Guid("524c5d54-ce07-4447-9ed1-38bd4e959c53"), FirstName = "Robert", Genre = "Thriller", LastName = "Ludlum" }
                    );
                });

            modelBuilder.Entity("BookStoreV2.Entities.Book", b =>
                {
                    b.Property<Guid>("BookdId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("BookdId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book","dbo");
                });

            modelBuilder.Entity("BookStoreV2.Entities.Book", b =>
                {
                    b.HasOne("BookStoreV2.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
